### ISSUE TITLE
Operational problem

### ISSUE THREAD

**Issue by wsfk716** [forchchch/DisenBooth#4]
Hello, following the Readme steps, I don't know why I didn't run it, except that I downloaded the local load because I couldn't link to huggingface.  
Traceback (most recent call last):
  File "/data/disk1/sxtang/Project/DisenBooth/train_disenbooth.py", line 1147, in <module>
    main(args)
  File "/data/disk1/sxtang/Project/DisenBooth/train_disenbooth.py", line 1026, in main
    img_state = img_adapter(img_state)
  File "/data/disk1/sxtang/anaconda3/envs/Dreambooth2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/disk1/sxtang/Project/DisenBooth/disen_net.py", line 16, in forward
    out_feature = self.adapter( self.sigmoid(self.mask)*feature ) + self.sigmoid(self.mask)*feature
RuntimeError: The size of tensor a (768) must match the size of tensor b (1024) at non-singleton dimension 2

**Comment by forchchch** [comment]
the problem may be that you use the wrong openclip version，note that for stable diffusion 2-1 base，we use open clip-H，instead of L
